### ISSUE TITLE
Support custom HTML templates

### ISSUE THREAD

**Issue by feeltheajf** [zitadel/saml#88]
**Is your feature request related to a problem? Please describe.**
Hardcoded HTML templates do not offer any customisation (to improve branding or security). For instance, we have a strict [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), which does not allow inline scripts and we do not want to have unnecessary exclusions.

**Describe the solution you'd like**
Allow to configure custom HTML templates.

**Describe alternatives you've considered**
I cannot think of any.

**Additional context**
See https://github.com/zitadel/saml/pull/89.

**Comment by livio-a** [comment]
Hey @feeltheajf 

Thank you for the issue (and implementation). While there are for sure some workarounds for CSP (e.g. hash) and the form itself should not get displayed to the user, but i totally get your requirement. Will check the PR now.
